case "$doc_type" in
	man)
		repl_items=(\
			name \
			meta_date \
			version \
			short_descr \
			synopsis \
			description \
			options \
			arguments \
			examples \
			seealso)
		output="$(cat "${tmpl_file[$doc_type]}")"
		;;
	help)
		repl_items=(\
			short_descr \
			synopsis \
			options)
		output="$(sed -E -e '1G;1a # DO NOT EDIT THIS FILE. Instead, edit corresponding file in subfolder prep/ and run make prep.' "${tmpl_file[$doc_type]}")"
		;;
	readme)
		repl_items=(\
			name \
			short_descr \
			description \
			installation \
			dependencies \
			rationale \
			synopsis \
			options \
			arguments \
			examples)
		output="$(cat "${tmpl_file[$doc_type]}")"
		;;
	*) _die "wrong option";;
esac
