.TH <name> 1 "<meta_date>" "v<version>" "User commands"
.SH NAME
<name> \- <short_descr>
.SH SYNOPSIS
<synopsis>
.SH DESCRIPTION
<description>
.SH OPTIONS
<options>
.SH ARGUMENTS
<arguments>
.SH EXAMPLES
<examples>
.SH SEE ALSO
<seealso>
.SH BUGS
Bugs and suggestions should be reported at: https://github.com/bashdroid/<name>/issues

.SH AUTHOR
https://github.com/bashdroid
